### ISSUE TITLE
Error at Post AQL query

### ISSUE THREAD

**Issue by miquelQida** [crs4/openEHR-tool#15]
If try to save an AQL query the error "_AQL Parse exception: line 1: char 0 mismatched input '{' expecting SELECT" arises.

Just comment line 813 at ehrbase_routines.py and it works.

  \#  aqltext="{'q':'"+aqltext+"'}"

**Comment by sasurfer** [comment]
I apologize for the delay. I was not watching this repo. You are right. The q is not needed anymore when storing the query. I update the code asap
